from typing import Any, Tuple, List

class DisplaySize:
    x: float
    y: float

class IO:
    display_size: DisplaySize
    want_capture_mouse: bool

class DrawList:
    def add_circle_filled(self, x: float, y: float, radius: float, color: int) -> None: ...

# Core functions used by the project (minimal stubs for type checking)
def get_io() -> IO: ...

def new_frame() -> None: ...

def render(draw_data: Any = ...) -> None: ...

def get_draw_data() -> Any: ...

def get_background_draw_list() -> DrawList: ...

def create_context() -> None: ...

def get_color_u32_rgba(r: float, g: float, b: float, a: float) -> int: ...

# Common color/style indices used by the Python imgui binding
COLOR_TEXT: int

def begin(name: str) -> None: ...

def end() -> None: ...

def text(s: str) -> None: ...

def separator() -> None: ...

def combo(label: str, current: int, items: List[str]) -> Tuple[bool, int]: ...

def button(label: str) -> bool: ...

def same_line(pos: float = 0.0) -> None: ...

def begin_child(name: str, height: int = 0, border: bool = False) -> None: ...

def end_child() -> None: ...

def text_unformatted(s: str) -> None: ...

def is_item_hovered() -> bool: ...

def set_tooltip(s: str) -> None: ...

def push_style_color(idx: int, r: float, g: float, b: float, a: float) -> None: ...

def pop_style_color() -> None: ...

def get_window_width() -> float: ...
